### ISSUE TITLE
[設計] トークナイズのメンバ変数とメンバ関数（基本的流れ）

### ISSUE THREAD

**Issue by s1-haya** [s1-haya/minishell_bonus#69]
・pull req
　→https://github.com/s1-haya/minishell_bonus/pull/73

**Comment by YungTatyu** [comment]
【気になった点】
・命名規則
　→tokenではじまっているものとはじまっていないものとばらつきがある
・prompt
　→「command line」「line」がベター？
・構造体s_tokenの中身
　□e_word_typeとe_opereator_typeが二つあるので分かりにくい
　　→token_typeでまとめられるならまとめたい
